name: Sync to Compte B

on:
  push:
    branches:
      - main 
  workflow_dispatch: # <--- C'EST LA NOUVELLE LIGNE MAGIQUE !

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du Compte A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer SSH
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key && chmod 600 ~/.ssh/deploy_key

      - name: Envoyer vers le Compte B
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote remove destination || true
          git remote add destination git@github.com:snenizoubeir-sketch/MiraDiabiCare.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" git push destination main --force
